name: Laravel Rsync Deploy

on:
  push:
    branches:
      - main
jobs:
  laravel-rsync-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: MilesChou/composer-action/7.3/install@master
        with:
            args: apt update && apt install php7.3-intl
      - run: |
          cp .env.example .env
          php artisan key:generate --ansi

      - name: Pull Docker image
        run: |
          docker pull "node:lts-slim"

      - name: Laravel Rsync Deploy
        uses: SHSharkar/Laravel-Rsync-Deploy@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRET_KEY }}
          ARGS: "--ignore-times --compress --verbose --exclude=.git --exclude=.github --exclude=node_modules --no-perms --no-owner --no-group --recursive"
          REMOTE_HOST: ${{ secrets.SECRET_HOST }}
          REMOTE_HOST_PORT: ${{ secrets.SECRET_PORT }}
          REMOTE_USER: ${{ secrets.SECRET_USER }}
          TARGET_DIRECTORY: /var/www/mvpbex/
